//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Xamarin.Forms.Xaml.XamlResourceIdAttribute("Xamarin_TabbedPage_Sample.BookmarkPage.xaml", "BookmarkPage.xaml", typeof(global::Xamarin_TabbedPage_Sample.BookmarkPage))]

namespace Xamarin_TabbedPage_Sample {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("BookmarkPage.xaml")]
    public partial class BookmarkPage : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(BookmarkPage));
        }
    }
}
